name: islami_app
description: "Islami App built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  introduction_screen: ^4.0.0
  google_fonts: ^8.0.2
  carousel_slider: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/islamic-logo-design.png
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/files/Hadeeth/
    - assets/files/Suras/
    - assets/icon/islamic-logo-design.png